### ISSUE TITLE
Version 3.5

### ISSUE THREAD

**Issue by tomchristie** [tomchristie/django-rest-framework#4549]
* Requests Client
* API Client
* ~~Hypermedia support~~
* API Client Uploads & Downloads
* RAML Support & Docs
* Schema fixes & Schema generation API
* Validation codes
* ~~Technical error handlers~~
* Fix 1.10 deprecation warnings
* Add `HTML_SELECT_CUTOFF`, `HTML_SELECT_CUTOFF_TEXT` settings
* Add `SCHEMA_COERCE_PATH_PK`, `SCHEMA_COERCE_METHOD_NAMES` settings.

---

- [x] API Client - Credentials.
- [x] API Client - Headers.
- [x] API Client & Requests Client - Documentation.
- [x] API Client & Requests Client - ~~allow_external / reverse hosts etc~~.
- [ ] ~~Document client library uploads/downloads.~~ - Let's just refer to the more complete docs.
- [ ] ~~Hypermedia support. (see #4241)~~ Pushing some of this back to 3.6
- [x] Validation error codes. (see #3775)
- [x] Finalize RAML support. (preliminary)
- [x] Review Swagger support - examples/types, basePath/not at root, examples. (see #4384)
- [x] Review Django REST swagger integration.
- [x] Document RAML support.
- [x] Schema fixes & new schema generation API.
- [x] Document schema generation API. (And limitations)
- [x] Formalize `get_schema_fields()` API.
- [ ] ~~Document Cli, CoreJSON, CoreAPI.~~
- [ ] ~~Check remaining 1.10 deprecation warnings on tests.~~
- [x] Root node when using schemas (how to hyperlink?)
- [x] Schema view
- [x] Deprecation warnings (Both deal with those raised by Django 1.10, and move along any `PendingDeprecation`)
- [x] `pk` -> `id` in schema generation.
- [x] Media type for CoreJSON
- [x] Update schema examples. (New shortcut, and pk/id)
- [x] Deprecate Router init args for schemas.
- [ ] ~~Technical error handlers~~ Deferred. Tracking under #4556.
- [ ] ~~Register views with routers~~
- [x] Review #4401 "Schemas should automatically respect API root location"
- [x] Resolve https://github.com/core-api/python-openapi-codec/issues/20
- [x] Resolve https://github.com/tomchristie/django-rest-framework/pull/4507
- [x] Resolve https://github.com/tomchristie/django-rest-framework/issues/4591
- [x] Ensure file uploads and downloads in `API clients` docs adequately documented or linked too.
- [x] Note media type for CoreJSON
- [ ] Resolve https://github.com/core-api/python-openapi-codec/issues/23
- [ ] Resolve https://github.com/core-api/python-client/issues/106
- [ ] Resolve https://github.com/core-api/python-client/issues/107
