### ISSUE TITLE
Schema generation ignores Serializer Meta options

### ISSUE THREAD

**Issue by mcgeeco** [tomchristie/django-rest-framework#5021]
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [X] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Add an option such as `read_only` or `help_text` to a serializer field using the `extra_kwargs` Meta option on the serializer, and check the Core API schema generated from this serializer.

## Expected behavior
The read_only or help_text values should be reflected in the generated schema.

## Actual behavior
Options added in this way don't appear to be recognised when the schema is generated.

Sorry, I looked for an existing issue for this but it was difficult to search for. I'm actually not sure if I've gotten the expected behaviour right here or not, so I thought I'd check first before trying to put together a fix.
Thanks!

**Comment by tomchristie** [comment]
Closing as per https://github.com/tomchristie/django-rest-framework/pull/5022#issuecomment-289403654
